//
//  Dashboard.m
//  StackMobStarterProject
//
//  Created by kakadais on 9/2/13.
//  Copyright (c) 2013 StackMob. All rights reserved.
//

#import "Dashboard.h"


@implementation Dashboard

@dynamic admission_date;
@dynamic admit_to_hospital;
@dynamic admitted;
@dynamic anal_sensation;
@dynamic asia_lighttouch_l;
@dynamic asia_lighttouch_l_subtotal;
@dynamic asia_lighttouch_r;
@dynamic asia_lighttouch_r_subtotal;
@dynamic asia_lighttouch_total;
@dynamic asia_motor_l;
@dynamic asia_motor_l_subtotal;
@dynamic asia_motor_r;
@dynamic asia_motor_r_subtotal;
@dynamic asia_motor_total;
@dynamic asia_pinpric_l;
@dynamic asia_pinpric_l_subtotal;
@dynamic asia_pinpric_r;
@dynamic asia_pinpric_r_subtotal;
@dynamic asia_pinpric_total;
@dynamic asia_score;
@dynamic billingcode;
@dynamic brace_required;
@dynamic complete_or_incomplete;
@dynamic createddate;
@dynamic dashboard_id;
@dynamic date_of_birth;
@dynamic date_of_surgery;
@dynamic degree_kyphosis;
@dynamic diagnosis_details;
@dynamic discharge_date;
@dynamic event_0;
@dynamic event_1;
@dynamic event_2;
@dynamic event_3;
@dynamic event_4;
@dynamic event_5;
@dynamic event_6;
@dynamic event_7;
@dynamic event_8;
@dynamic event_9;
@dynamic event_10;
@dynamic event_11;
@dynamic event_12;
@dynamic event_13;
@dynamic event_14;
@dynamic event_15;
@dynamic event_16;
@dynamic event_17;
@dynamic event_18;
@dynamic event_19;
@dynamic event_20;
@dynamic event_21;
@dynamic event_22;
@dynamic event_23;
@dynamic event_24;
@dynamic event_days;
@dynamic follow_up_required;
@dynamic fracture_morphology_type;
@dynamic fracturetype;
@dynamic hangman;
@dynamic healthcard_number;
@dynamic height_loss;
@dynamic injurylevel;
@dynamic injurytype;
@dynamic lastmoddate;
@dynamic n_motor_l;
@dynamic n_motor_r;
@dynamic n_sensory_l;
@dynamic n_sensory_r;
@dynamic neurologic_status;
@dynamic neurological_level;
@dynamic neurologicallyintact;
@dynamic occur_date;
@dynamic option2;
@dynamic patient_admitted_to_icu;
@dynamic patient_discharged_to;
@dynamic patient_received_allogenic_blood;
@dynamic patient_status;
@dynamic plc;
@dynamic requires_step_down_bed;
@dynamic site_id;
@dynamic status;
@dynamic surgery_required;
@dynamic surgical_billing_code;
@dynamic tlic_score;
@dynamic tlic_score_total;
@dynamic translation;
@dynamic trauma;
@dynamic visit_type;
@dynamic voluntary_anal_contraction;
@dynamic z_motor_l;
@dynamic z_motor_r;
@dynamic z_sensory_l;
@dynamic z_sensory_r;
@dynamic zone_partial_preservation;
@dynamic event_16_0;
@dynamic event_16_1;
@dynamic event_16_2;
@dynamic event_16_3;
@dynamic event_19_0;
@dynamic event_19_1;
@dynamic event_19_2;
@dynamic event_22_0;
@dynamic event_22_1;
@dynamic event_23_0;
@dynamic event_23_1;

@end
